### ISSUE TITLE
Cannot make bsp

### ISSUE THREAD

**Issue by yangkex** [sequencer/playground#23]
Hello, I tried to build the env and `git submodule update --init` success, but `make bsp` failed as below.
Thank you!

```
mill -i mill.bsp.BSP/install
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at mill.main.client.IsolatedMillMainLoader.runMain(IsolatedMillMainLoader.java:58)
        at mill.main.client.MillClientMain.main(MillClientMain.java:67)
Caused by: java.util.NoSuchElementException: key not found: ammonite.$file.dependencies.chisel-testers2.build
        at scala.collection.MapOps.default(Map.scala:274)
        at scala.collection.MapOps.default$(Map.scala:273)
        at scala.collection.AbstractMap.default(Map.scala:405)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:425)
        at mill.main.GraphUtils$.scriptNodeOf$1(GraphUtils.scala:16)
        at mill.main.GraphUtils$.$anonfun$linksToScriptNodeGraph$1(GraphUtils.scala:16)
        at scala.collection.immutable.List.map(List.scala:250)
        at scala.collection.immutable.List.map(List.scala:79)
        at mill.main.GraphUtils$.scriptNodeOf$1(GraphUtils.scala:16)
        at mill.main.GraphUtils$.$anonfun$linksToScriptNodeGraph$2(GraphUtils.scala:22)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:396)
        at scala.collection.immutable.Set$.from(Set.scala:353)
        at scala.collection.immutable.Set$.from(Set.scala:93)
        at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
        at scala.collection.IterableOps.map(Iterable.scala:675)
        at scala.collection.IterableOps.map$(Iterable.scala:675)
        at scala.collection.AbstractIterable.map(Iterable.scala:926)
        at mill.main.GraphUtils$.linksToScriptNodeGraph(GraphUtils.scala:22)
        at mill.main.RunScript$.importTree(RunScript.scala:139)
        at mill.main.RunScript$.$anonfun$runScript$6(RunScript.scala:81)
        at ammonite.util.Res$Success.map(Res.scala:67)
        at mill.main.RunScript$.runScript(RunScript.scala:71)
        at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:119)
        at mill.main.MainRunner.watchLoop2(MainRunner.scala:67)
        at mill.main.MainRunner.runScript(MainRunner.scala:92)
        at mill.MillMain$.main0(MillMain.scala:310)
        at mill.MillMain$.main(MillMain.scala:52)
        at mill.MillMain.main(MillMain.scala)
        ... 6 more
make: *** [Makefile:21: bsp] Error 1
```

**Comment by ZenithalHourlyRate** [comment]
https://github.com/com-lihaoyi/mill/issues/1788#issuecomment-1073016514

**Comment by yangkex** [comment]
Thank you! I downgrade to 0.10.0 and it works.
